version: '3'

services:
    app:
        build: .
        entrypoint: ./.docker/entrypoint.sh
        # entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
        container_name: api-jest-store
        ports:
            - 3000:3000

        volumes: 
            - .:/home/node/app
        
        depends_on:
            - db
    db: 
        build: .docker/postgres
        container_name: api-jest-store-db
        restart: always
        tty: true
        environment: 
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=store
            - ./docker/dbdata:/var/lib/postgresql/data    
    pgadmin: 
        image: dpage/pgadmin4
        container_name: api-jest-store-pgadmin4
        tty: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@user.com 
            - PGADMIN_DEFAULT_PASSWORD=123456
        ports:
            - 9011:80
